sudo: false
addons:
    apt:
        packages:
            # Build dependencies for Python: {
            - build-essential
            - zlib1g-dev
            - libreadline-dev
            - libncursesw5-dev
            - libssl-dev
            - libgdbm-dev
            - libsqlite3-dev
            - liblzma-dev
            - libc6-dev
            - tk-dev
            - libdb-dev
            # }
            - bzr
            # Runtime dependencies for Python: {
            - zlib1g
            - libssl1.0.0
            # }
            - curl
os:
    - linux
language:
    - python
before_install:
    - openssl aes-256-cbc -K $encrypted_9875d026deea_key -iv $encrypted_9875d026deea_iv -in keys/id_rsa.enc -out keys/id_rsa -d
install:
    - ./scripts/install.sh
script:
    - ./scripts/build.sh
after_success:
    - ./scripts/deploy.sh
matrix:
    include:
        - python: "2.6"
          env: >-
              SCRIPT1="./scripts/build-zsh-and-zpython.sh"
              SCRIPT2="./scripts/build-vim.sh v7.0.112"
              SCRIPT3="./scripts/build-vim.sh master"
              SCRIPT4="./scripts/create-wheels.sh"
        - python: "2.7"
          env: >-
              SCRIPT1="./scripts/build-zsh-and-zpython.sh"
              SCRIPT2="./scripts/build-vim.sh v7.0.112"
              SCRIPT3="./scripts/build-vim.sh master"
              SCRIPT4="./scripts/create-wheels.sh"
        - python: "3.2"
          env: >-
              SCRIPT1="./scripts/build-zsh-and-zpython.sh"
              SCRIPT2="./scripts/build-vim.sh master"
              SCRIPT3="./scripts/create-wheels.sh"
        - python: "3.3"
          env: >-
              SCRIPT1="./scripts/build-zsh-and-zpython.sh"
              SCRIPT2="./scripts/build-vim.sh master"
              SCRIPT3="./scripts/create-wheels.sh"
        - python: "3.4"
          env: >-
              SCRIPT1="./scripts/build-zsh-and-zpython.sh"
              SCRIPT2="./scripts/build-vim.sh master"
              SCRIPT3="./scripts/create-wheels.sh"
        - python: "pypy"
          env: >-
              SCRIPT1="./scripts/create-wheels.sh"
        - python: "pypy3"
          env: >-
              SCRIPT1="./scripts/create-wheels.sh"
        - python: "2.6"
          env: >-
              SCRIPT1="./scripts/build-ucs2-cpython.sh 2.6"
              SCRIPT2="./scripts/build-vim.sh master 2.6"
              SCRIPT3="./scripts/build-vim.sh v7.0.112 2.6"
              SCRIPT4="./scripts/build-zsh-and-zpython.sh 2.6"
              SCRIPT5="./scripts/create-ucs2-wheels.bash 2.6"
        - python: "2.7"
          env: >-
              SCRIPT1="./scripts/build-ucs2-cpython.sh 2.7"
              SCRIPT2="./scripts/build-vim.sh master 2.7"
              SCRIPT3="./scripts/build-vim.sh v7.0.112 2.7"
              SCRIPT4="./scripts/build-zsh-and-zpython.sh 2.7"
              SCRIPT5="./scripts/create-ucs2-wheels.bash 2.7"
        - env: >-
              SCRIPT1="./scripts/build-tmux.sh 1.6"
              SCRIPT2="./scripts/build-tmux.sh 1.7"
              SCRIPT3="./scripts/build-tmux.sh 1.8"
              SCRIPT4="./scripts/build-tmux.sh 1.9"
              SCRIPT5="./scripts/build-tmux.sh 2.0"
              SCRIPT6="./scripts/build-tmux.sh 2.1"
        - env: >-
              SCRIPT1="./scripts/build-fish.sh"
              SCRIPT2="./scripts/build-libvterm.sh"
              SCRIPT3="./scripts/build-command-t.sh"
              SCRIPT4="./scripts/archive-plugins.sh"
              SCRIPT5="./scripts/build-rc.sh"
# vim: noet ts=4 sts=4 sw=4 ft=yaml
