sudo: false
dist: trusty
addons:
    apt:
        packages:
            # Build dependencies for Python: {
            - build-essential
            - zlib1g-dev
            - libreadline-dev
            - libncursesw5-dev
            - libssl-dev
            - libgdbm-dev
            - libsqlite3-dev
            - liblzma-dev
            - libc6-dev
            - tk-dev
            - libdb-dev
            # }
            # Runtime dependencies for Python: {
            - zlib1g
            - libssl1.0.0
            # }
            - curl
            - ruby
            - ruby-all-dev
            - bzr
            - libevent-dev
os: linux
language: python
before_install: |
    openssl aes-256-cbc \
            -K $encrypted_9875d026deea_key \
            -iv $encrypted_9875d026deea_iv \
            -in keys/id_rsa.enc \
            -out keys/id_rsa \
            -d
install: ./scripts/install.sh
script: ./scripts/build.sh
after_success: ./scripts/deploy.sh
matrix:
    include:
        - python: "2.6"
          env: "SCRIPTS='
              ./scripts/build-zsh-and-zpython.sh;
              ./scripts/build-vim.sh v7.0.112;
              ./scripts/build-vim.sh master;
              ./scripts/create-wheels.sh;
          '"
        - python: "2.7"
          env: 'SCRIPTS="
              ./scripts/build-zsh-and-zpython.sh;
              ./scripts/build-vim.sh v7.0.112;
              ./scripts/build-vim.sh master;
              ./scripts/create-wheels.sh;
          "'
        - python: "3.2"
          env: 'SCRIPTS="
              ./scripts/build-zsh-and-zpython.sh;
              ./scripts/build-vim.sh master;
              ./scripts/create-wheels.sh;
          "'
        - python: "3.3"
          env: 'SCRIPTS="
              ./scripts/build-zsh-and-zpython.sh;
              ./scripts/build-vim.sh master;
              ./scripts/create-wheels.sh;
          "'
        - python: "3.4"
          env: 'SCRIPTS="
              ./scripts/build-zsh-and-zpython.sh;
              ./scripts/build-vim.sh master;
              ./scripts/create-wheels.sh;
          "'
        - python: "3.5"
          env: 'SCRIPTS="
              ./scripts/build-zsh-and-zpython.sh;
              ./scripts/build-vim.sh master;
              ./scripts/create-wheels.sh;
          "'
        - python: "pypy"
          env: 'SCRIPTS="
              ./scripts/create-wheels.sh;
          "'
        - python: "pypy3"
          env: 'SCRIPTS="
              ./scripts/create-wheels.sh;
          "'
        - python: "2.7"
          env: 'SCRIPTS="
              ./scripts/build-ucs2-cpython.sh 2.7;
              ./scripts/build-vim.sh master 2.7;
              ./scripts/build-vim.sh v7.0.112 2.7;
              ./scripts/build-zsh-and-zpython.sh 2.7;
              ./scripts/create-ucs2-wheels.bash 2.7;
          "'
        - env: 'SCRIPTS="
              ./scripts/build-tmux.sh 1.6;
              ./scripts/build-tmux.sh 1.7;
              ./scripts/build-tmux.sh 1.8;
              ./scripts/build-tmux.sh 1.9;
              ./scripts/build-tmux.sh 2.0;
              ./scripts/build-tmux.sh 2.1;
              ./scripts/build-tmux.sh 2.2;
              ./scripts/build-tmux.sh 2.3;
              ./scripts/build-tmux.sh 2.4;
          "'
        - language: cpp
          compiler: gcc-6
          env: 'SCRIPTS="
              ./scripts/build-fish.sh;
              ./scripts/build-libvterm.sh;
              ./scripts/build-command-t.sh;
              ./scripts/archive-plugins.sh;
              ./scripts/build-rc.sh;
          "'
          addons:
              apt:
                  sources:
                      - llvm-toolchain-precise
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-6
                      - g++-6
# vim: noet ts=4 sts=4 sw=4 ft=yaml
